# Generated by Django 4.0.5 on 2022-09-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='comment_name',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
