# Generated by Django 4.0.5 on 2022-09-10 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
