# Generated by Django 4.0.5 on 2022-09-10 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
