# Generated by Django 4.0.5 on 2022-09-10 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_blogcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
